### ISSUE TITLE
Show Mana Curve When Hovering Over Weapons/Minons/Spells/Mana [premium]

### ISSUE THREAD

**Issue by cpriest** [supertriodo/Arena-Tracker#109]
It would be really nice to see a mana curve graph (along with a list of cards) when hovering over the Minon / Weapon / Spells / Mana Average areas on the Mechanics overlay.

I can put this (similar) request in another ticket if you like, but:

A hover display explaining how the Deck Weight is being modified or showing which cards are modifying the weight of the deck.  Perhaps even an indicator during card selection that will alter the average mana cost of the deck.

**Comment by cpriest** [comment]
P.S.  Thanks for your efforts, I became a premium user some year or more ago and have continued on as such.

**Comment by supertriodo** [comment]
Hi Clint,
Thanks for your long time patreon support.

**About your first request:** 

During the development of the mechanics feature I decided to not show the list of cards involved on Minion/weapon/spells because it was going to be a big list that wouldn't really add any info as you can very easily check on your deck list, where weapons and spells have different text colors than minions.

I also thought about the idea of adding a mana curve but that is already given by HS, separating the mana curve on 3 different sections Weapon / Spells / Minions it's an interesting idea, it's fancy but I don't really think is something people would use.

I don't say I won't work on it. It's just that my developing time is limited and I have to choose where to spend it.

**About your second request:**

There's an old post in patreon that I think will answer all the question you have about deck average element: https://www.patreon.com/posts/deck-weight-18353665

If you are interested in knowing much more about these mechanics the user guide is a great place: https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/drafting-tab.html#mechanics

At the end of that user guide section there is a link to all the patreon post with information about these mechanics, including the deck average element I first linked.
https://www.patreon.com/triodo/posts?tag=Draft%20Mechanics

If you have any other question or request, I'm here to help.
I'll let this post here as a reminder or your request.
