### ISSUE TITLE
[bug] arena draft information makes no sense

### ISSUE THREAD

**Issue by astranberg** [supertriodo/Arena-Tracker#131]
Sometimes it's on, sometimes it's off. Here's an example:

![Hearthstone Screenshot 08-23-21 20 02 08](https://user-images.githubusercontent.com/18320423/130539157-a073e6db-4998-4320-a6e2-2d0afd3cdd2d.png)

1. Kindling elemental - telling my about two drops, pings and AOE. Makes no sense.
2. Emerald sky - tells me how many 3 mana drops I have...
3. Hog Rancher - tells me how many card draws I have....
4. All of them have no HSR winrate or HA rating

EDIT:
On the very next decision, you'll notice the leftmost card also has no HSR winrate or HA rating. Yet, it's still telling my about potential two drops. Is this a bug when it doesn't recognize a card?

![HS_Screenshot_2](https://user-images.githubusercontent.com/18320423/130539442-ba109875-052f-49d6-9259-e8fb4b99c857.png)

**Comment by supertriodo** [comment]
Hi @astranberg 

The problem here is that AT its failing on its recognition of cards.
Wild pyro or any of the other 2 cards recognized aren't in the current rotation of arena, which means AT has built the wrong pool of cards to recognize.

Go to AT dir, remove Histograms dir and start AT.

If it still fails send me your logs as explained in the user guide:
https://triodo.gitbook.io/arena-tracker-documentation/#i_setup_the_app_but_it_doesnt_work_it_didnt_upload_my_arena_game_it_didnt_start_drafting

Let me know how it goes, we will fix this.

**Comment by supertriodo** [comment]
Is this solved?

**Comment by astranberg** [comment]
> Is this solved?

Yes! Sorry for the late reply. Thanks for the help!

Maybe place in an FAQ if not already.

**Comment by supertriodo** [comment]
Nice!
