### ISSUE TITLE
issue with HSTracker

### ISSUE THREAD

**Issue by vaidab** [supertriodo/Arena-Tracker#22]
Both HSTracker and Arena-Tracker ask me to restart if one is active. I think it's because they both need the logfile directory to be in their own place. Can you make this integration possible? I'd love to use both.

**Comment by supertriodo** [comment]
AT ask you to restart hs when log.config has changed, but  it only  add the
missing lines. Probably is the other tracker the one which remove info.

El 17/8/2016 9:06, "vaidab" <notifications@github.com> escribió:

Both HSTracker and Arena-Tracker ask me to restart if one is active. I
think it's because they both need the logfile directory to be in their own
place. Can you make this integration possible? I'd love to use both.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/supertriodo/Arena-Tracker/issues/22>, or mute the thread

**Comment by bmichotte** [comment]
Hi, what do you use in Arena Tracker ? 

HSTracker use (and need) *Power, Net, Asset, Bob, Rachelle, Arena, LoadingScreen and FullScreenFX*, all with this config
```
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
```

**Comment by vaidab** [comment]
Hi,
How can I find out?

**Comment by supertriodo** [comment]
This is a log.config example for AT

https://github.com/supertriodo/Arena-Tracker/issues/8

**Comment by vaidab** [comment]
I don't have any log.config file for AT.  Searched in App Support and also in its homedir.

**Comment by supertriodo** [comment]
~/Library/Preferences/Blizzard/Hearthstone/log.config

**Comment by vaidab** [comment]
Here it is:

[Power]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[Net]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[Asset]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[Bob]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[Rachelle]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[Arena]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[LoadingScreen]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false
[FullScreenFX]
LogLevel=1
FilePrinting=true
ConsolePrinting=false
ScreenPrinting=false

[Zone]
LogLevel=1
FilePrinting=true

**Comment by supertriodo** [comment]
Any improve in this, is up to HSTracker to avoid removing lines from log.config to let both trackers coexist.
