### ISSUE TITLE
Doesn't save between sessions

### ISSUE THREAD

**Issue by Amathon** [supertriodo/Arena-Tracker#47]
Every time I restart ArenaTracker the stats are completely reset.
The card list from the current arena run are reset as well. When clicking on "arena" the list gets populated but there are always 4-6 "Unknown" cards in the tracker.
Is this intended behavior? If not - how do I fix that?

**Comment by supertriodo** [comment]
> Every time I restart ArenaTracker the stats are completely reset.
For now AT uses Arena Mastery to store your arena stats, so create an account on that web and (fill your user/password)[https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/config-tab.html#arenamastery]. The next arena you draft with AT will be uploaded and their games. I'm working right now on an integration with track-o-bot stats system.

> The card list from the current arena run are reset as well. When clicking on "arena" the list gets populated but there are always 4-6 "Unknown" cards in the tracker.
That's because AT get the cards of your deck from HS log and duplicates don't appear there. In this case you can [tweak your deck](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/player-deck-window.html#tweakdeck) to add the missing copies.

This happens because you didn't use AT while the drafting. If you do, a file with the whole deck info will be saved on your AT dir and will be used next time you access the arena, so you won't see unknown cards.

Cheers

**Comment by Amathon** [comment]
I already entered my Arena Mastery login details.

<img width="227" alt="screen shot 2017-05-16 at 12 52 46" src="https://cloud.githubusercontent.com/assets/827651/26102760/c675aa38-3a36-11e7-86e1-58adc679d16a.png">

I already did like 3 arenas with AT (the drafting is amazing by the way), still after closing and reopening AT all stats and duplicate cards in the deck list are gone.

Cheers

**Comment by supertriodo** [comment]
Do arenas and/or games upload to your arenamastery account?

After you start an arena or play an arena game does the games change to green or red?
Red means there has been a problem in the upload, green means they have been uploaded correctly.

**Comment by supertriodo** [comment]
https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/games-tab.html#games-tab-

**Comment by supertriodo** [comment]
Looking at the code both of your problems are connected. Only if you retreive the last arena from your ArenaMastery account when you start AT you will be able to complete your deck. This is something I have to fix for the next release where I get rid of Arena Mastery.

For now for your proble, make sure your Arena Mastery account doens't have an old arena, if so go the website and remove the latest arena before starting a new one.

**Comment by Amathon** [comment]
Jep, that works

<img width="243" alt="screen shot 2017-05-16 at 13 10 29" src="https://cloud.githubusercontent.com/assets/827651/26103300/1d42c786-3a39-11e7-9670-acff004d0a97.png">

![screen shot 2017-05-16 at 13 10 42](https://cloud.githubusercontent.com/assets/827651/26103334/3ba532c2-3a39-11e7-915d-ac7d061ad2fe.png)

I just deleted all arenas from Arena Master, restarted AT and it seems to work now! Stats and deck list are up to date.

Thanks for your support, looking forward to the next updates!

**Comment by supertriodo** [comment]
Great :smile:
