### ISSUE TITLE
Card recognition issue

### ISSUE THREAD

**Issue by nokomm3nt** [supertriodo/Arena-Tracker#58]
I am using AT on Mac and I often encounter an issue that I do not move the HS window but the cards are not or mistakenly recognized. I could not resolve it by moving the mouse away from the cards.
It would be also very useful if you could continue an arena draft after clicking the force draft button or have a separate button for 'force continue draft' in such cases.

**Comment by supertriodo** [comment]
Since I did the recognition rework is imposible to not reconize the card, it just can take more time until AT show the result, as the time pass on the threshold for recognition is widen so after 10 seconds it will always give you a result. 

If there are golden cards involved the recognition can fail for some card, but this shouldn't happen to often. If the recognition fail you can continue the draft by picking the card you want, the card chosen will be the correct one even if it was badly recognized by AT.

What you want about the continue force draft is already implemented. When you do a force draft AT start your draft with you actual deck (for HearthArena purpose), but using it doesn't mean is going to recognize the cards corrrectly this time, it will probably fail with the exact same pack. It's an useful option if you have  a half-way draft from yesterday, in this case enter the arena, fill your deck with the missing duplicates (by double clicking the cards on deck window) and force draft.

Also, while you are already in a draft with AT you can force draft and will stop the old one and start a new one with your current deck, but again I don't see much of a reason for this, maybe I didn't understand well you problem.

If this helps, or it's not what you where asking let me know :)

**Comment by nokomm3nt** [comment]
Thanks for the quick and detailed response, there is no issue to solve. :)
