### ISSUE TITLE
Card scores not updating after a pick

### ISSUE THREAD

**Issue by Gekuu9** [supertriodo/Arena-Tracker#60]
I run the app, everything seems to be working fine, I start a mage arena run, scores come up for the cards on the screen, but after I pick, they don't change. The only way to update them is to manually start a whole new arena run, which throws out the deck.

**Comment by supertriodo** [comment]
I guess [this is the problem](
https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/faq.html#drafting_doesnt_read_next_card)
you are experimenting

If thats the case, the reason for not showing the new card scores is
because Hearthstone is not writting correctly in its log. To know exactly
the cause I would need you to send me the file arenatrackerLog.txt from
USER/Arena Tracker

Hope this helps.

**Comment by Gekuu9** [comment]
Here it is: https://pastebin.com/DZRTG22Q

**Comment by supertriodo** [comment]
The log shows that Hearthstone is not writting in its log. Did you restart
Hearthstone after the first run? If not, do it. If you did it, you can
force AT to reconfigure Hearthstone log again by reseting AT (do ctrl-R
with AT on focus).
