### ISSUE TITLE
Boulderfist Ogre Score Does not match Lightforge score  - 40

### ISSUE THREAD

**Issue by DuggieHS** [supertriodo/Arena-Tracker#61]
I don't recall the number exactly, I think it said  boulderfist ogre was 86 --> which translates to 126, when Boulderfist is 104, so it should read as 64 in arena tracker.

**Comment by supertriodo** [comment]
Hey Duggie, glad you give it a try to AT.

When come to card recognition, AT can sometimes fail recognizing the card, this generally only happen whith golden cards, due to having a dinamic image.

From all my test one of the card that it's the more guilty of fail recognition is golden ogre, that is generally recognized as cult master.

To be sure what are the cards that AT recognized you can check the main window ([draft tab](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/drafting-tab.html#draftingtab)) where the three recognized cards are shown.
