### ISSUE TITLE
Bug: Card tracking not working with new hs update

### ISSUE THREAD

**Issue by AgustinCroce** [supertriodo/Arena-Tracker#74]
After the last hs update (October 17) the card tracking stop working for both player deck and oponent deck

**Comment by supertriodo** [comment]
https://www.reddit.com/r/ArenaTracker/comments/775r94/support_my_work_on_patreon_if_you_enjoy_arena/

**Comment by supertriodo** [comment]
**Update**: AT is right now broken due to the last HS patch. Thx to the support of the community I can work on keeping AT updated. If you enjoy this app, don't let it die, support it on [patreon](https://www.patreon.com/triodo), it's only 2$.

**The new release is already available first for [patreons](https://www.patreon.com/triodo)**, I really want to thank to the people who showed that [amazing support](https://www.reddit.com/r/ArenaTracker/comments/775r94/support_my_work_on_patreon_if_you_enjoy_arena/).

[![Patreon](https://c5.patreon.com/external/logo/become_a_patron_button.png)](https://www.patreon.com/triodo)

**Comment by supertriodo** [comment]
The free version of Arena Tracker has also been released.
