### ISSUE TITLE
ArenaTrackerLog.txt, ArenaTrackerDecks.json, card images location (HSCards dir) and .config dir name.

### ISSUE THREAD

**Issue by frangi** [supertriodo/Arena-Tracker#9]
These should all go into the user's home directory (~/.config/Arena Tracker). I have patched it myself locally to distribute them in this dir tree:

~/.config/arena-tracker/cards
~/.config/arena-tracker/logs
~/.config/arena-tracker/decks

The reasoning behind this is that if this program is properly packaged (it goes in /usr/bin/) a subdirectory there with 777 permission has NO place to exist.

You might have also noticed I changed the main dir name: it's good practice in unix filesystems to have the names all lowercase and use no space.

**Comment by supertriodo** [comment]
I am a linux user myself but Arena Tracker is cross-platform app.

Most windows user will have Arena Tracker in their desktop and having just one directory is much more convenient. Anyway HSCards have grown big since I created the app so its true it needs some organization inside.

The directory Arena Tracker is just the container in the zip, you can rename it or remove it if you want.

Right now there is no packaging for Arena Tracker so I don't see the worry for separate files in /home and /usr/bin
