### ISSUE TITLE
Witchwood Grizzly not recognized?

### ISSUE THREAD

**Issue by TerribleNews** [supertriodo/Arena-Tracker#95]
This is the second time I've been unable to get Arena Tracker to recognize Witchwood Grizzly. It's not even an option in the pulldown menu. 
![arenatracker_screenshot](https://user-images.githubusercontent.com/1923071/42605872-b37aa080-8550-11e8-9f54-dc06f3e3f8ec.jpg)

**Comment by supertriodo** [comment]
Thanks for the feedback.

It seems the art of Witchwood Grizzly was changed some days ago and I didn't notice. AT is still looking for the old art, that's why is failing.

[Here](https://www.reddit.com/r/hearthstone/comments/8w5uxe/official_change_to_witchwood_grizzlys_art_to_make/) you can check the old and new art.

I'll update the card. I'll let you know when is ready.

**Comment by supertriodo** [comment]
I have updated the card. I will force a redownload of all card in the next release coming in a few days.

If you want to force the redownload now. Go to [AT dir](https://arena-tracker.gitbooks.io/arena-tracker-documentation/content/en/installation.html#ATdir), remove Hearthstone Cards dir and restart AT.
