### ISSUE TITLE
Choose Card Suggestions not working

### ISSUE THREAD

**Issue by petertkim** [supertriodo/Arena-Tracker#96]
![image](https://user-images.githubusercontent.com/35403143/43682010-30f8cc3e-982b-11e8-8e08-4118a78ebf35.png)

ArenaTracker app isn't working while I am drafting.  I tried restarting hearthstone and ctrl-R on arenatracker and it still wont work.

Please help!

Thanks!

Peter

Update:

![image](https://user-images.githubusercontent.com/35403143/43682042-7859500c-982c-11e8-854a-de331be5e98b.png)

It started working but its showing totally random cards instead of the ones I'm choosing between.  Are the values the correct ones or are they for the random cards?

Any idea how to fix this??

**Comment by supertriodo** [comment]
AT has recognized HS window in the wrong zone of the screen (as you can see by the position of the scores, they should be behing the cards).

Try to force draft to make AT to look for the location of the HS window again. Also don't move the HS window until the end of the draft or AT will keep analizing and incorrect part of the scren.

Hope it helps,
Triodo

**Comment by supertriodo** [comment]
If AT doesn't recognize correctly where the cards are the suggestion are going to be wrong because it is looking in a zone of the screen where the cards aren't.

Which is your OS and version?

Once AT has recognized were HS is it will show the scores below the cards like in [this image](https://github.com/supertriodo/Arena-Tracker/blob/master/Readme/DraftCombined.png)
If you check the numbers are not below the cards AT is going to fail in every single cards, it is just reading the wrong zone, you need to force draft again to let AT locate where the cards are and don't move HS window from the moment you click force draft until the moment you end your draft.
